source "https://rubygems.org"

gem "fastlane", '2.221.1'
# gem 'dotenv', groups: [:aiwushe, :community]
gem 'dotenv', '2.8.1'
gem 'cocoapods', '1.15.2'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
